apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  job1:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
    outputs:
      output1: hello
      output2: world
  # job2 works fine because it needs job1
  job2:
    needs: job1
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
  #job3 does not work fine because it does not declare needs job1, and it executes before job1
  job3:
    # needs: job1
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
  #job4 does not work fine because it does not declare needs job1, but it executes after job1! :( 
  job4:
    needs: job2
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
  #job5 does not work fine because it needs job1
  job5:
    needs: [job1,job2]
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
